<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LP-TZD-0X101846" failures="1" tests="3" name="Test" time="27.009" errors="0" timestamp="2024-08-08T01:25:05 IST">
  <testcase classname="day46.OrangeHRM" name="testLogo" time="0.06"/>
  <testcase classname="day46.OrangeHRM" name="testURL" time="0.015">
    <failure type="java.lang.AssertionError" message="expected [https://opesource-demo.orangehrmlive.com/web/index.php/auth/login] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]">
      <![CDATA[java.lang.AssertionError: expected [https://opesource-demo.orangehrmlive.com/web/index.php/auth/login] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]
at day46.OrangeHRM.testURL(OrangeHRM.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testURL -->
  <testcase classname="day46.OrangeHRM" name="testTitle" time="0.0">
    <skipped/>
  </testcase> <!-- testTitle -->
</testsuite> <!-- Test -->
